apiVersion: v1
kind: Service
metadata:
  name: {{ template "unleash.fullname" . }}
spec:
  type: NodePort 
  selector:
    app: {{ template "unleash.fullname" . }}
  ports:
    - protocol: TCP
      port: 4242
      nodePort: 30002
      targetPort: 4242